name: flutter_face_api
description: 
  This is a flutter module for compairing faces using phone`s camera. 
version: 5.1.3
homepage: "https://github.com/regulaforensics/flutter_face_api"

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.regula.faceapi.flutter_face_api
        pluginClass: FlutterFaceApiPlugin
      ios:
        pluginClass: FlutterFaceApiPlugin